services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ggggg
      POSTGRES_DB: giolotrello_dev
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

  api:
    build: .
    volumes:
      - .:/app
    environment:
      DATABASE_URL: "ecto://postgres:ggggg@db:5432/giolotrello_dev"
      SECRET_KEY_BASE: "SOME_SECRET_KEY"
      MIX_ENV: dev
    depends_on:
      - db
    command: >
      sh -c "
      until nc -z db 5432; do
        echo 'Waiting for Postgres...';
        sleep 1;
      done;
      mix ecto.migrate &&
      mix phx.server
      "
    ports:
      - "4000:4000"
    restart: unless-stopped

  client:
    build:
      context: ../giolotrello_client
    volumes:
      - ../giolotrello_client:/app
      - /app/deps
      - /app/_build
    environment:
      SECRET_KEY_BASE: "ANOTHER_SECRET_KEY"
      MIX_ENV: dev
      BACKEND_URL: "http://api:4000"
    depends_on:
      - api
    ports:
      - "3000:4000"

volumes:
  db_data:
